[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "torch>=1.9.0",
    "torchvision>=0.10.0",
    "torchaudio>=0.9.0",
    "tensorboard",
    "scipy>=1.6.3",
    "numpy",
    "control"
]
build-backend = "setuptools.build_meta"